print("--- APP STARTING ---")
import os
import traceback
import base64
from flask import Flask, request, make_response, render_template, render_template_string, jsonify
from weasyprint import HTML
import datetime

app = Flask(__name__)

# Full Legal Disclaimer for PDF
PDF_DISCLAIMER = """
All cost evaluations, asset measurements, and predictive material output parameters generated by CostPredict are automated configurations provided solely for baseline budgeting and scoping evaluations. These values do not constitute structural advice, architectural blueprints, shipping and freight, or binding contractual pricing guarantees. Actual regional material rates, labor availability, and construction engineering demands will vary by project conditions. Users must independently verify all bills of quantities with a licensed professional contractor prior to project execution.
"""

# Embedded PDF Template (Notice the logo src uses base64 now)
PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; font-size: 11px; }
        .header { background-color: #23408A; padding: 20px; text-align: center; color: white; margin-bottom: 20px; }
        .logo { max-height: 60px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #23408A; color: white; padding: 6px; text-align: left; }
        th.center { text-align: center; }
        td { padding: 6px; border-bottom: 1px solid #eee; }
        td.center { text-align: center; }
        .group-header { background-color: #f0f0f0; font-weight: bold; }
        .totals { font-weight: bold; background-color: #fafafa; }
        .grand-total { font-weight: bold; background-color: #23408A; color: white; }
        .footer { margin-top: 50px; font-size: 8px; text-align: justify; border-top: 1px solid #ccc; padding-top: 10px; color: #555; line-height: 1.4; }
    </style>
</head>
<body>
    <div class="header">
        <img src="data:image/png;base64,{{ logo_b64 }}" class="logo" alt="CostPredict Logo">
        <h1 style="margin: 0; font-size: 20px;">Predictive Estimate</h1>
    </div>
    <p><strong>Date Printed:</strong> {{ data.date }} | <strong>Type:</strong> {{ data.project_type }} | <strong>Quality:</strong> {{ data.quality_level }} | <strong>Zip:</strong> {{ data.zip_code }}</p>
    <table>
        <thead>
            <tr>
                <th>Item Details</th>
                <th class="center">CONFIDENCE<br>SCORE</th>
                <th>Unit Cost x Qty</th>
                <th>Min</th>
                <th>Avg</th>
                <th>Max</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data.items %}
                {% if item.is_header %}
                    <tr class="group-header"><td colspan="6">{{ item.name }}</td></tr>
                {% else %}
                    <tr>
                        <td>{{ item.type }}</td>
                        <td class="center">{{ item.conf_pct }}%<br><span style="font-size:9px">{{ item.conf_label }}</span></td>
                        <td>{{ item.u_cost }}</td>
                        <td>${{ item.min }}</td>
                        <td>${{ item.avg }}</td>
                        <td>${{ item.max }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        <tfoot>
            <tr class="totals"><td>Material Subtotal</td><td colspan="2"></td><td>${{ data.mat_sub_min }}</td><td>${{ data.mat_sub_avg }}</td><td>${{ data.mat_sub_max }}</td></tr>
            <tr class="totals"><td>Labor Subtotal</td><td colspan="2"></td><td>${{ data.lab_sub_min }}</td><td>${{ data.lab_sub_avg }}</td><td>${{ data.lab_sub_max }}</td></tr>
            <tr class="totals"><td>Sales Tax ({{ data.tax_rate_display }}%)</td><td colspan="2"></td><td>${{ data.tax_min }}</td><td>${{ data.tax_avg }}</td><td>${{ data.tax_max }}</td></tr>
            <tr class="grand-total"><td>Grand Total</td><td colspan="2"></td><td>${{ data.tot_min }}</td><td>${{ data.tot_avg }}</td><td>${{ data.tot_max }}</td></tr>
        </tfoot>
    </table>
    <div class="footer">
        {{ disclaimer }}
    </div>
</body>
</html>
"""

def get_golden_catalog():
    return {
        "01-General-Requirements": [
            {"name": "Dumpster Rental (30 Yd)", "unit": "Weeks", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Site Protection / Ram Board", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Low"},
            {"name": "Temporary Fencing", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Scaffold Rental", "unit": "Days", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Portable Toilet", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Jobsite Office Trailer", "unit": "Months", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Safety Signage", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Fire Extinguisher", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Temporary Power Pole", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Water Tank (250 Gal)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "03-Concrete": [
            {"name": "Ready Mix", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Rebar", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Anchor Bolts", "unit": "Count", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Wire Mesh", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Concrete Curing Compound", "unit": "Gallons", "default_waste": 2, "labor_difficulty": "Low"},
            {"name": "Expansion Joint Filler", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Form Release Agent", "unit": "Gallons", "default_waste": 2, "labor_difficulty": "Low"},
            {"name": "Concrete Nails", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Vapor Barrier", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Fiber Reinforcement", "unit": "Bags", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Concrete Pigment", "unit": "Bags", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Styrofoam Void Forms", "unit": "Count", "default_waste": 5, "labor_difficulty": "Low"}
        ],
        "04-Masonry": [
            {"name": "Brick", "unit": "Count", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Block", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Mortar", "unit": "Bags", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Stone Veneer", "unit": "Sq. Ft.", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Weep Vents", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Wall Ties", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Lintels", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Glass Block", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Masonry Cleaner", "unit": "Gallons", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Water Repellent Sealer", "unit": "Gallons", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Flashing", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Backer Rod", "unit": "Linear Ft.", "default_waste": 2, "labor_difficulty": "Low"}
        ],
        "05-Metals": [
            {"name": "Steel Beam", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Metal Stud", "unit": "Count", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Track", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Decking", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Steel Plates", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Structural Tubing", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Bolts/Nuts", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Welding Rods", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Metal Primer", "unit": "Gallons", "default_waste": 2, "labor_difficulty": "Low"},
            {"name": "Handrails", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Metal Lath", "unit": "Sheets", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Fasteners (Self-Tapping)", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"}
        ],
        "06-Rough-Carpentry": [
            {"name": "2x4 Studs", "unit": "Count", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "2x6 Joists", "unit": "Count", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "4x8 Plywood", "unit": "Sheets", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "OSB", "unit": "Sheets", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "LVL Beams", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Framing Nails (Collated)", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Construction Adhesive", "unit": "Tubes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Joist Hangers", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Hurricane Ties", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Sill Plate Anchor Bolts", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Tyvek House Wrap", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Flashing Tape", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"}
        ],
        "07-Thermal": [
            {"name": "R-13 Batt", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "R-30 Batt", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Rigid Foam", "unit": "Sheets", "default_waste": 8, "labor_difficulty": "Medium"},
            {"name": "Spray Foam", "unit": "Board Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Mineral Wool", "unit": "Bags", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Vapor Retarder", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Acoustic Sealant", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Insulation Staples", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Reflective Foil", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Foundation Insulation", "unit": "Sheets", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Pipe Insulation", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Expansion Foam", "unit": "Cans", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "08-Doors": [
            {"name": "Interior Door", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Exterior Door", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Door Frame", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Hinges", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Door Handle/Lockset", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Threshold", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Weatherstripping", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Door Closer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Kick Plate", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Door Stop", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Shims", "unit": "Bundles", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Casing (Trim)", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"}
        ],
        "09-Drywall": [
            {"name": "Panel 4x8", "unit": "Sheets", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Fire-Rated 5-8", "unit": "Sheets", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Tape", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Compound", "unit": "Boxes", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Corner Bead", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Drywall Screws", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Backer Board (Cement)", "unit": "Sheets", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Sanding Mesh", "unit": "Packs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Primer", "unit": "Gallons", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Access Panel", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Shims/Spacers", "unit": "Packs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Texture Spray", "unit": "Cans", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "10-Flooring": [
            {"name": "Hardwood", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "LVP", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Tile", "unit": "Sq. Ft.", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Laminate", "unit": "Sq. Ft.", "default_waste": 7, "labor_difficulty": "Medium"},
            {"name": "Underlayment", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Thin-set Mortar", "unit": "Bags", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Grout", "unit": "Bags", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Transition Strips", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Shoe Molding", "unit": "Linear Ft.", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Self-Leveling Compound", "unit": "Bags", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Adhesive", "unit": "Buckets", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Carpet Tiles", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Low"}
        ],
        "11-Equipment": [
            {"name": "Refrigerator", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Dishwasher", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Range", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Microwave", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Washer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Dryer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Range Hood", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Garbage Disposal", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Water Heater", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Wine Cooler", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Wall Oven", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Trash Compactor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "12-Cabinets": [
            {"name": "Wall 30in", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Base 36in", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Pantry", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Crown Molding", "unit": "Linear Ft.", "default_waste": 15, "labor_difficulty": "High"},
            {"name": "Cabinet Hardware (Knobs)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Cabinet Hardware (Pulls)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Drawer Slides", "unit": "Pairs", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Hinge Sets", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Filler Strips", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Toe Kick Molding", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Under-Cabinet Lighting", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Mounting Screws", "unit": "Boxes", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "13-Countertops": [
            {"name": "Granite", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Quartz", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Laminate", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Butcher Block", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Marble Slab", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Backsplash Tile", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Silicone Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Epoxy Adhesive", "unit": "Kits", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Support Brackets", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Sealer", "unit": "Bottles", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Sink Cut-out Template", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Edge Trim", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"}
        ],
        "21-Fire-Suppression": [
            {"name": "Sprinkler Head", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Piping", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Control Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Extinguisher", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Smoke Detector", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Heat Detector", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Alarm Bell", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Flow Switch", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Gauge", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Hanger/Bracket", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Fire-Rated Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Exit Signage", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "22-Plumbing": [
            {"name": "PEX Tubing", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "PVC Pipe", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Toilet", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Shower Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Kitchen Faucet", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Drain Trap (P-Trap)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Supply Line", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Shut-off Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Pipe Hangers", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "PVC Glue/Primer", "unit": "Kits", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Wax Ring", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Pipe Insulation", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Low"}
        ],
        "23-HVAC": [
            {"name": "Condenser", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Air Handler", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Thermostat", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Ductwork", "unit": "Linear Ft.", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Vent Cover/Grille", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Refrigerant Lines", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Air Filter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Flexible Duct Connectors", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Duct Tape (Foil)", "unit": "Rolls", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Drain Pan", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Condensate Pump", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Hanging Straps", "unit": "Rolls", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "26-Electrical": [
            {"name": "12-2 Romex", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Main Panel", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Outlets", "unit": "Count", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Can Lights", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Electrical Boxes", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Wire Nuts", "unit": "Boxes", "default_waste": 2, "labor_difficulty": "Low"},
            {"name": "Conduit Pipe (PVC)", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Light Switches", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Grounding Rod", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Breakers", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Ceiling Fan Rough-in", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Electrical Tape", "unit": "Rolls", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "27-Communications": [
            {"name": "Cat6 Cable", "unit": "Linear Ft.", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Coax Cable", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Router", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Patch Panel", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Wall Plate (Data)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "RJ45 Connectors", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Cable Ties", "unit": "Packs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "J-Hooks", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Fiber Optic Cable", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Switch Hub", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Cable Conduit", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Labeling Kit", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "31-Earthwork": [
            {"name": "Excavation", "unit": "Hours", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Grading", "unit": "Sq. Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Gravel", "unit": "Tons", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Trenching", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Fill Dirt", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Silt Fence", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Low"},
            {"name": "Geotextile Fabric", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Compaction Testing", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Rip Rap", "unit": "Tons", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Backfill Material", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Survey Stakes", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Dewatering Pump Rental", "unit": "Days", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "32-Exterior": [
            {"name": "Asphalt", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Pavers", "unit": "Sq. Ft.", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Sod", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Mulch", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Concrete Curbing", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Landscape Lighting", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Sprinkler Head (Lawn)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Topsoil", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Edging Material", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Retaining Wall Block", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Drainage Pipe", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Planting Soil", "unit": "Bags", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "33-Utilities": [
            {"name": "Water Main Pipe", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Sewer Pipe", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Catch Basin", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Backflow Preventer", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Manhole Cover", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Water Meter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Cleanout Access", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Gas Shut-off Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Electric Conduit (Large)", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Transformer Pad", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Pull Box", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Warning Tape", "unit": "Rolls", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "34-Transportation": [
            {"name": "Traffic Signs", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Bollards", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Parking Stops", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Striping Paint", "unit": "Gallons", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Speed Bumps", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Reflector Studs", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Guard Rail Sections", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Directional Arrows", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Ticket Dispenser", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Gate Arm", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Curb Ramps", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Wheel Stops", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "40-Process": [
            {"name": "Industrial Pump", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Process Motor", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Inline Filter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Control Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Pressure Gauge", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Flow Meter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Seals/Gaskets", "unit": "Kits", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Stainless Steel Pipe", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Pipe Hangers (Heavy Duty)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Vibration Isolators", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Insulation Jacket", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Thermal Sensor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "41-Material-Handling": [
            {"name": "Hoist", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Dock Leveler", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Straps", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Safety Netting", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Conveyor Rollers", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Pallet Racking Upright", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Pallet Racking Beam", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Safety Bollards", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Floor Anchors", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Guide Rails", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Chain Hoist", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Identification Signage", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "42-Process-Heating": [
            {"name": "Industrial Boiler", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Burner Assembly", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "High-Temp Piping", "unit": "Linear Ft.", "default_waste": 8, "labor_difficulty": "High"},
            {"name": "Steam Vent", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Heat Exchanger", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Control Panel", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Refractory Brick", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Insulation Blanket", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Temperature Probe", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Expansion Tank", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Fuel Line", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Draft Inducer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "43-Gas-Liquid": [
            {"name": "Compressor", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Pressure Tank", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Gas Regulator", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "High-Pressure Hose", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Pressure Relief Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Quick-Connect Fitting", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Filter Dryer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Sight Glass", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Leak Detection Sensor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Mounting Base", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Liquid Level Switch", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Hydraulic Fluid", "unit": "Gallons", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "44-Pollution-Control": [
            {"name": "Air Scrubber Media", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Exhaust Ducting", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Emissions Monitor", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Neutralizing Chemical", "unit": "Gallons", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Activated Carbon Filter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "HEPA Filter Element", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Containment Berm", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Oil-Water Separator", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Sample Port", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Exhaust Stack", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Fan/Blower Motor", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Vibration Dampener", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "45-Industrial": [
            {"name": "Conveyor Section", "unit": "Linear Ft.", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Gearbox Drive", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Heavy Machine Mount", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Proximity Sensor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Emergency Stop Button", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "PLC Module", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Cable Tray", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Motor Starter", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Safety Guarding", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Warning Strobe", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Coupling Element", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Grease Fitting", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"}
        ],
        "46-Water-Systems": [
            {"name": "Filtration Pump", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Filter Media", "unit": "Bags", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Water Treatment Pipe", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Chemical Feed Valve", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "UV Sterilizer", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Reverse Osmosis Membrane", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Backwash Controller", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Storage Tank", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Chemical Storage Drum", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Pipe Union", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Pressure Transducer", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Sampling Faucet", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "48-Electrical-Power": [
            {"name": "Step-Down Transformer", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Industrial Switchgear", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "High-Voltage Cable", "unit": "Linear Ft.", "default_waste": 8, "labor_difficulty": "High"},
            {"name": "Heavy Grounding Rod", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Bus Bar", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Circuit Breaker (Large)", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Surge Protector", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Cable Lug", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Terminal Block", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Disconnect Switch", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Phase Monitor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "High-Voltage Warning Sign", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "50-Roofing": [
            {"name": "Architectural Shingles", "unit": "Squares", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Underlayment", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Drip Edge", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Ice & Water Shield", "unit": "Rolls", "default_waste": 7, "labor_difficulty": "Medium"},
            {"name": "Roofing Nails", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Ridge Vent", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Flashing (Valley)", "unit": "Rolls", "default_waste": 10, "labor_difficulty": "High"},
            {"name": "Pipe Boot", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Roof Cement", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Starter Shingles", "unit": "Bundles", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Step Flashing", "unit": "Count", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Ridge Caps", "unit": "Bundles", "default_waste": 5, "labor_difficulty": "Medium"}
        ],
        "51-Siding": [
            {"name": "Vinyl Panel", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Fiber Cement Board", "unit": "Sq. Ft.", "default_waste": 12, "labor_difficulty": "High"},
            {"name": "Starter Strip", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "House Wrap", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "J-Channel", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Corner Posts", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Siding Nails", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Window/Door Trim", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "F-Channel", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Soffit Panel", "unit": "Sq. Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Fascia Board", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"}
        ],
        "52-Windows": [
            {"name": "Double Hung", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Slider", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Casement", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Flashing Tape", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Shim Kit", "unit": "Packs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Low-Expansion Foam", "unit": "Cans", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Exterior Trim Coil", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Interior Casing", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Window Sill", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Screen Mesh", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Safety Glass Film", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"}
        ],
        "53-Insulation": [
            {"name": "Blown Cellulose", "unit": "Bags", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Foil Radiant Barrier", "unit": "Sq. Ft.", "default_waste": 8, "labor_difficulty": "Medium"},
            {"name": "Acoustic Insulation", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Insulation Staples", "unit": "Boxes", "default_waste": 10, "labor_difficulty": "Low"},
            {"name": "Spray Foam Kit", "unit": "Kits", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Vapor Barrier Tape", "unit": "Rolls", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Rigid Foam Board", "unit": "Sheets", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Mineral Wool Batts", "unit": "Sq. Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Attic Baffles", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Insulation Knives", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Protective Mask", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Wall Cavity Sealant", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "54-Ceilings": [
            {"name": "Drop Ceiling Tile", "unit": "Count", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Main Grid Runner", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Cross Tee", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Ceiling Wire", "unit": "Rolls", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Wall Molding", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Hanger Eyelet", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Acoustic Sealant", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Grid Splices", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Toggle Bolts", "unit": "Boxes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Ceiling Paint", "unit": "Gallons", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Patch Plaster", "unit": "Tubs", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Access Door", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "55-Columns": [
            {"name": "Fiberglass Column", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Wood Wrap Column", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Column Base/Capital", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Structural Steel Post", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Shim Plates", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Adhesive (Heavy Duty)", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Anchor Bolts", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Primer", "unit": "Quarts", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Exterior Paint", "unit": "Gallons", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Fasteners (Screws)", "unit": "Boxes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Column Plinth", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "56-Molding": [
            {"name": "Baseboard", "unit": "Linear Ft.", "default_waste": 15, "labor_difficulty": "Medium"},
            {"name": "Crown Molding", "unit": "Linear Ft.", "default_waste": 20, "labor_difficulty": "High"},
            {"name": "Door/Window Casing", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Chair Rail", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Quarter Round", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Low"},
            {"name": "Finish Nails", "unit": "Boxes", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Wood Filler", "unit": "Tubs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Paintable Caulk", "unit": "Tubes", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Mitre Saw Blades", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Glue", "unit": "Bottles", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Corner Blocks", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Sandpaper", "unit": "Packs", "default_waste": 0, "labor_difficulty": "None"}
        ],
        "57-Fencing": [
            {"name": "Wood Picket", "unit": "Count", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Fence Post (4x4)", "unit": "Count", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Rail/Stringer", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Concrete Mix (Post)", "unit": "Bags", "default_waste": 5, "labor_difficulty": "High"},
            {"name": "Gate Hardware", "unit": "Kits", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Chain Link Mesh", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Tension Bar", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Post Cap", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Gate Hinges", "unit": "Pairs", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Fence Stain", "unit": "Gallons", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Bracing/Bracket", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Gravel (Base)", "unit": "Bags", "default_waste": 0, "labor_difficulty": "Medium"}
        ],
        "58-Specialties": [
            {"name": "Signage", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Lockers", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Toilet Partitions", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Fire Extinguisher Cabinet", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Wall Guards", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Corner Guards", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Projection Screen", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Flagpole", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Postal Specialties", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Storage Shelving", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Safety Mirrors", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Entrance Mats", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"}
        ],
        "59-Furnishings": [
            {"name": "Window Blinds", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Curtain Tracks", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Waste Receptacles", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Wall Clocks", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Bench Seating", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Art/Wall Decor", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Cubicle Panels", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Desk Hardware", "unit": "Kits", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Coat Racks", "unit": "Count", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Floor Mats", "unit": "Count", "default_waste": 0, "labor_difficulty": "None"},
            {"name": "Mirrors", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Furniture Glides", "unit": "Packs", "default_waste": 0, "labor_difficulty": "Low"}
        ],
        "60-Landscaping": [
            {"name": "Shrubs", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Trees", "unit": "Count", "default_waste": 0, "labor_difficulty": "High"},
            {"name": "Flower Bed Border", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Irrigation Tubing", "unit": "Linear Ft.", "default_waste": 10, "labor_difficulty": "Medium"},
            {"name": "Sprinkler Controller", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"},
            {"name": "Landscape Fabric", "unit": "Rolls", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Decorative Stone", "unit": "Tons", "default_waste": 5, "labor_difficulty": "Medium"},
            {"name": "Bark/Mulch", "unit": "Cu. Yards", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Garden Edging", "unit": "Linear Ft.", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Fertilizer", "unit": "Bags", "default_waste": 0, "labor_difficulty": "Low"},
            {"name": "Grass Seed", "unit": "Bags", "default_waste": 5, "labor_difficulty": "Low"},
            {"name": "Tree Stakes", "unit": "Count", "default_waste": 0, "labor_difficulty": "Medium"}
        ]
    }

def get_conf_label(pct):
    if pct >= 80: return "Great"
    elif pct >= 60: return "Good"
    elif pct >= 50: return "Toss-Up"
    elif pct >= 21: return "Not Good"
    else: return "Poor"

def get_tax_rate(zip_code):
    return 0.0825

def calculate_estimate_data(payload):
    project_info = payload.get('project_info', {}) or {}
    materials = payload.get('materials', []) or []
    
    # 1. Risk Multiplier Logic
    risk_months = int(payload.get('risk_months', 0))
    risk_mult = 1 + (0.005 * risk_months)
    
    # 2. Date Penalty Calculation (Months into the future)
    start_date_str = project_info.get('startDate', '')
    months_to_start = 0
    if start_date_str:
        try:
            start_d = datetime.datetime.strptime(start_date_str, "%Y-%m-%d")
            now = datetime.datetime.now()
            months_to_start = max(0, (start_d.year - now.year) * 12 + start_d.month - now.month)
        except Exception:
            pass

    # 3. Zip Code Penalty (simulated local variance based on zip numbers)
    zip_str = str(project_info.get('zipCode', '00000'))
    zip_penalty = sum(int(digit) for digit in zip_str if digit.isdigit()) % 5
    
    q_level = project_info.get('qualityLevel', 'Standard Grade')
    quality_mult = 0.85 if q_level == 'Budget Grade' else (1.3 if q_level == 'Luxury Grade' else 1.0)
    market_idx = 1.05
    tax_rate = get_tax_rate(project_info.get('zipCode', '00000'))
    
    processed_items = []
    mat_sub = [0,0,0]; lab_sub = [0,0,0]
    conversions = {"Cu. Yards": 27, "sqyd": 9, "sqft": 1, "linear foot": 1, "each": 1}
    catalog = get_golden_catalog()

    for item in materials:
        cat = item.get('category', 'Unknown')
        sub = item.get('subcategory', 'Unknown')
        
        try:
            qty = float(item.get('quantity') or 0)
            waste = float(item.get('waste') or 0)
        except ValueError:
            qty, waste = 0.0, 0.0
            
        labor_req = item.get('labor', False)
        
        effective_rate = 15.00 * quality_mult * market_idx * risk_mult
        multiplier = conversions.get("sqft", 1)
        final_qty = (qty * multiplier) * (1 + (waste / 100.0))
        
        mat_avg = final_qty * effective_rate
        lab_avg = (mat_avg * 0.6) if labor_req else 0

        # Confidence Algorithm
        difficulty = "Medium"
        if cat in catalog:
            for cat_item in catalog[cat]:
                if cat_item["name"] == sub:
                    difficulty = cat_item.get("labor_difficulty", "Medium")
        
        diff_penalty = 5 if difficulty == "High" else (2 if difficulty == "Medium" else 0)
        
        # Base confidence drops 1.5% per month in the future
        mat_conf = max(15, int(95 - (months_to_start * 1.5) - zip_penalty))
        lab_conf = max(10, int(92 - (months_to_start * 1.5) - zip_penalty - diff_penalty))

        processed_items.append({"is_header": True, "name": f"{cat} - {sub}"})
        
        processed_items.append({
            "is_header": False, "type": "Material", 
            "conf_pct": mat_conf, "conf_label": get_conf_label(mat_conf), 
            "u_cost": f"${effective_rate:,.2f} x {final_qty:,.1f}", 
            "min": f"{mat_avg*0.85:,.2f}", "avg": f"{mat_avg:,.2f}", "max": f"{mat_avg*1.25:,.2f}"
        })
        
        if labor_req:
            processed_items.append({
                "is_header": False, "type": "Labor", 
                "conf_pct": lab_conf, "conf_label": get_conf_label(lab_conf), 
                "u_cost": "-", 
                "min": f"{lab_avg*0.85:,.2f}", "avg": f"{lab_avg:,.2f}", "max": f"{lab_avg*1.25:,.2f}"
            })
        
        mat_sub[0]+=mat_avg*0.85; mat_sub[1]+=mat_avg; mat_sub[2]+=mat_avg*1.25
        lab_sub[0]+=lab_avg*0.85; lab_sub[1]+=lab_avg; lab_sub[2]+=lab_avg*1.25

    tax_arr = [(mat_sub[i] + lab_sub[i]) * tax_rate for i in range(3)]
    tot_arr = [(mat_sub[i] + lab_sub[i]) + tax_arr[i] for i in range(3)]

    return {
        "date": datetime.datetime.now().strftime("%B %d, %Y"),
        "project_type": project_info.get('projectType', 'N/A'), 
        "quality_level": q_level, 
        "zip_code": project_info.get('zipCode', 'N/A'),
        "items": processed_items,
        "mat_sub_min": f"{mat_sub[0]:,.2f}", "mat_sub_avg": f"{mat_sub[1]:,.2f}", "mat_sub_max": f"{mat_sub[2]:,.2f}",
        "lab_sub_min": f"{lab_sub[0]:,.2f}", "lab_sub_avg": f"{lab_sub[1]:,.2f}", "lab_sub_max": f"{lab_sub[2]:,.2f}",
        "tax_rate_display": f"{tax_rate*100:.2f}",
        "tax_min": f"{tax_arr[0]:,.2f}", "tax_avg": f"{tax_arr[1]:,.2f}", "tax_max": f"{tax_arr[2]:,.2f}",
        "tot_min": f"{tot_arr[0]:,.2f}", "tot_avg": f"{tot_arr[1]:,.2f}", "tot_max": f"{tot_arr[2]:,.2f}"
    }

@app.route('/', methods=['GET'])
def index(): 
    try:
        return render_template('index.html')
    except Exception as e:
        print(f"Template Error: {e}")
        return f"Cannot load HTML: {e}", 500

@app.route('/api/catalog', methods=['GET'])
def get_catalog(): 
    return jsonify(get_golden_catalog())

@app.route('/api/calculate', methods=['POST'])
def calculate_totals(): 
    try:
        return jsonify(calculate_estimate_data(request.get_json()))
    except Exception as e:
        print("CALCULATION ERROR:")
        print(traceback.format_exc())
        return jsonify({"error": str(e)}), 500

@app.route('/api/report', methods=['POST'])
def generate_report():
    try:
        report_data = calculate_estimate_data(request.get_json())
        
        # BULLETPROOF PDF FIX: Read logo, convert to Base64 data string
        logo_b64 = ""
        logo_path = "CostPredict_Logo_White.png"
        if os.path.exists(logo_path):
            with open(logo_path, "rb") as img_file:
                logo_b64 = base64.b64encode(img_file.read()).decode('utf-8')
        else:
            print("WARNING: CostPredict_Logo_White.png not found in root.")

        html_content = render_template_string(
            PDF_TEMPLATE, 
            data=report_data, 
            disclaimer=PDF_DISCLAIMER, 
            logo_b64=logo_b64
        )
        
        # No base_url required, all assets are inline
        pdf = HTML(string=html_content).write_pdf()
        
        response = make_response(pdf)
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = 'attachment; filename="CostPredict_Takeoff.pdf"'
        return response
    except Exception as e:
        print("PDF ERROR:")
        print(traceback.format_exc())
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__': 
    app.run()
3. Full index.html
The only change here is ensuring the startDate is captured and sent to the backend so the python script has the data to crunch the new confidence scores.

HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CostPredict - Contractor Predictive Pricing</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .bg-brand-blue { background-color: #23408A; }
        .text-brand-blue { color: #23408A; }
        .bg-brand-yellow { background-color: #FFC113; }
        .border-brand-yellow { border-color: #FFC113; }
        .border-brand-blue { border-color: #23408A; }
    </style>
</head>
<body class="bg-gray-50 text-gray-800 font-sans min-h-screen flex flex-col">
    
    <header class="bg-white py-6 shadow-sm border-b-4 border-brand-yellow">
        <div class="max-w-5xl mx-auto px-4 flex flex-col items-center">
            <img src="/static/logo.png" alt="CostPredict Logo" class="h-12 mb-2">
            <p class="text-gray-500 font-bold text-sm tracking-wide uppercase">Contractor Predictive Pricing</p>
        </div>
    </header>

    <main class="flex-grow max-w-5xl mx-auto w-full p-4 md:p-8">
        <div id="form-container" class="bg-white p-6 md:p-8 rounded-xl shadow-lg border border-gray-200">
            <form id="estimate-form">
                <section class="mb-8">
                    <h2 class="text-2xl font-bold text-brand-blue mb-6 border-b-2 border-brand-yellow pb-2">Project Information</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                        <div>
                            <label class="block text-sm font-bold text-gray-700 mb-1">Project Type</label>
                            <select id="project-type" class="w-full p-3 border-2 border-gray-200 rounded-lg outline-none">
                                <option value="Residential">Residential</option><option value="Commercial">Commercial</option>
                                <option value="Mixed-Use">Mixed-Use</option><option value="Industrial">Industrial</option>
                            </select>
                        </div>
                        <div>
                            <label class="block text-sm font-bold text-gray-700 mb-1">Project Zip Code</label>
                            <input type="text" id="zip-code" class="w-full p-3 border-2 border-gray-200 rounded-lg outline-none" required>
                        </div>
                        <div>
                            <label class="block text-sm font-bold text-gray-700 mb-1">Quality Level</label>
                            <select id="quality-level" class="w-full p-3 border-2 border-gray-200 rounded-lg outline-none">
                                <option value="Budget Grade">Budget Grade</option><option value="Standard Grade">Standard Grade</option>
                                <option value="Luxury Grade">Luxury Grade</option>
                            </select>
                        </div>
                        <div>
                            <label class="block text-sm font-bold text-gray-700 mb-1">Estimated Purchase Date</label>
                            <input type="date" id="start-date" class="w-full p-3 border-2 border-gray-200 rounded-lg outline-none" required>
                        </div>
                    </div>
                </section>
                <section class="mb-8">
                    <h2 class="text-2xl font-bold text-brand-blue mb-6 border-b-2 border-brand-yellow pb-2">Material & Labor Specifications</h2>
                    <div id="materials-container"></div>
                    <button type="button" onclick="addMaterialRow()" class="mt-4 bg-gray-100 text-brand-blue font-bold px-6 py-3 rounded-lg hover:bg-brand-yellow transition">+ Add Another Material</button>
                </section>
                
                <button type="submit" class="w-full bg-brand-blue text-white font-bold py-4 rounded-lg hover:bg-blue-900 transition shadow-lg text-lg">Calculate Pricing</button>
            </form>
        </div>

        <div id="checkout-section" class="hidden bg-white p-6 md:p-8 rounded-xl shadow-lg border-2 border-brand-blue">
            <h2 class="text-2xl font-bold text-brand-blue mb-6 border-b-2 border-brand-yellow pb-2">Predictive Estimate</h2>
            <div class="mb-8 bg-blue-50 p-4 rounded-lg border border-blue-100">
                <label class="block text-lg font-bold text-brand-blue mb-2">Timeline Risk Shifter</label>
                <p class="text-sm text-gray-700 mb-4">Simulate timeline delays to account for projected inflation and localized market escalation.</p>
                <div class="flex items-center gap-4">
                    <span class="text-sm font-bold text-green-600">Target</span>
                    <input type="range" id="risk-slider" min="0" max="12" step="3" value="0" class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer">
                    <span class="text-sm font-bold text-red-600">+12 Months</span>
                </div>
                <div class="text-center mt-2 font-bold text-brand-blue">Shift: +<span id="risk-display">0</span> Months</div>
            </div>

            <div class="md:hidden text-center text-xs font-bold text-brand-blue bg-yellow-50 p-2 rounded mb-2">← Scroll Right to Read Full Estimate →</div>
            <div class="overflow-x-auto mb-8">
                <table class="w-full text-left border-collapse" id="checkout-table">
                    <thead><tr class="bg-gray-100 text-gray-700 text-sm uppercase">
                        <th class="p-3 border-b-2">Item</th>
                        <th class="p-3 border-b-2 text-center">Confidence<br>Score</th>
                        <th class="p-3 border-b-2 text-right">Unit Cost x Qty</th>
                        <th class="p-3 border-b-2 text-right text-green-700">Min</th>
                        <th class="p-3 border-b-2 text-right text-brand-blue">Avg</th>
                        <th class="p-3 border-b-2 text-right text-red-700">Max</th>
                    </tr></thead>
                    <tbody id="checkout-items"></tbody>
                </table>
            </div>
            <button type="button" onclick="editEstimate()" class="bg-gray-200 px-6 py-3 rounded-lg font-bold">← Back to Edit</button>
            <button type="button" id="download-pdf-btn" class="bg-brand-blue text-white px-6 py-3 rounded-lg font-bold">Print Predictive Report (PDF)</button>
        </div>
    </main>

    <footer class="bg-brand-blue text-white p-6 text-center mt-8">
        <p class="text-sm font-bold">&copy; 2026 CostPredict. All rights reserved.</p>
        <p class="text-xs mt-2 text-gray-300 max-w-4xl mx-auto text-justify">
            LEGAL DISCLAIMER: All cost evaluations, asset measurements, and predictive material output parameters generated by CostPredict are automated configurations provided solely for baseline budgeting and scoping evaluations. These values do not constitute structural advice, architectural blueprints, shipping and freight, or binding contractual pricing guarantees. Actual regional material rates, labor availability, and construction engineering demands will vary by project conditions. Users must independently verify all bills of quantities with a licensed professional contractor prior to project execution.
        </p>
    </footer>

    <script>
        let goldenCatalog = {};
        let currentPayload = {}; 

        document.addEventListener('DOMContentLoaded', async () => {
            const response = await fetch('/api/catalog');
            goldenCatalog = await response.json();
            document.getElementById('start-date').setAttribute('min', new Date().toISOString().split('T')[0]);
            addMaterialRow();
        });

        function renderTable(data) {
            let rowsHtml = data.items.map(i => 
                i.is_header ? `<tr class="bg-gray-100 font-bold border-b"><td colspan="6" class="p-3">${i.name}</td></tr>` 
                : `<tr><td class="p-3 border-b">${i.type}</td><td class="p-3 border-b text-center font-bold">${i.conf_pct}%<br><span class="text-xs font-normal text-gray-500">${i.conf_label}</span></td><td class="p-3 border-b text-right">${i.u_cost}</td><td class="p-3 border-b text-right">$${i.min}</td><td class="p-3 border-b text-right">$${i.avg}</td><td class="p-3 border-b text-right">$${i.max}</td></tr>`
            ).join('');
            
            let totalsHtml = `
                <tr class="bg-gray-50 font-bold border-t-2"><td colspan="3" class="p-3">Material Subtotal</td><td class="text-right p-3">$${data.mat_sub_min}</td><td class="text-right p-3">$${data.mat_sub_avg}</td><td class="text-right p-3">$${data.mat_sub_max}</td></tr>
                <tr class="bg-gray-50 font-bold"><td colspan="3" class="p-3">Labor Subtotal</td><td class="text-right p-3">$${data.lab_sub_min}</td><td class="text-right p-3">$${data.lab_sub_avg}</td><td class="text-right p-3">$${data.lab_sub_max}</td></tr>
                <tr class="bg-gray-50 font-bold"><td colspan="3" class="p-3">Sales Tax (${data.tax_rate_display}%)</td><td class="text-right p-3">$${data.tax_min}</td><td class="text-right p-3">$${data.tax_avg}</td><td class="text-right p-3">$${data.tax_max}</td></tr>
                <tr class="bg-brand-blue text-white font-bold text-lg"><td colspan="3" class="p-3">Grand Total</td><td class="text-right p-3">$${data.tot_min}</td><td class="text-right p-3">$${data.tot_avg}</td><td class="text-right p-3">$${data.tot_max}</td></tr>
            `;
            
            document.getElementById('checkout-items').innerHTML = rowsHtml + totalsHtml;
        }

        document.getElementById('risk-slider').addEventListener('input', async function() {
            document.getElementById('risk-display').textContent = this.value;
            currentPayload.risk_months = parseInt(this.value);
            
            try {
                const response = await fetch('/api/calculate', { 
                    method: 'POST', 
                    headers: {'Content-Type': 'application/json'}, 
                    body: JSON.stringify(currentPayload) 
                });
                const data = await response.json();
                renderTable(data);
            } catch (err) {
                console.error("Live calculation failed.", err);
            }
        });

        function addMaterialRow() {
            const container = document.getElementById('materials-container');
            const rowId = 'row-' + Date.now();
            container.insertAdjacentHTML('beforeend', `
                <div id="${rowId}" class="grid grid-cols-1 md:grid-cols-12 gap-4 items-end mb-6 p-5 border bg-gray-50 rounded-lg relative">
                    <button type="button" onclick="document.getElementById('${rowId}').remove()" class="absolute top-2 right-3 text-red-500 font-bold">×</button>
                    <div class="col-span-12 md:col-span-3">
                        <label class="block text-xs font-bold text-gray-500 uppercase">Main Material Category</label>
                        <input list="cats-${rowId}" class="main-cat-input w-full p-2 border rounded" required>
                        <datalist id="cats-${rowId}">${Object.keys(goldenCatalog).map(c => `<option value="${c}">`).join('')}</datalist>
                    </div>
                    <div class="col-span-12 md:col-span-3">
                        <label class="block text-xs font-bold text-gray-500 uppercase">Material Subcategory</label>
                        <input list="subs-${rowId}" class="sub-cat-input w-full p-2 border rounded" required disabled>
                        <datalist id="subs-${rowId}"></datalist>
                    </div>
                    <div class="col-span-6 md:col-span-2"><label class="block text-xs font-bold text-brand-blue uppercase">Qty</label><input type="number" class="qty-input w-full p-2 border rounded" value="0"></div>
                    <div class="col-span-6 md:col-span-2">
                        <label class="block text-xs font-bold text-gray-500 uppercase">Waste %</label>
                        <select class="waste-input w-full p-2 border rounded">
                            <option value="0">0%</option>
                            <option value="5">5%</option>
                            <option value="10">10%</option>
                            <option value="15">15%</option>
                            <option value="20">20%</option>
                        </select>
                    </div>
                    <div class="col-span-12 md:col-span-2"><input type="checkbox" class="labor-input" checked> <label class="text-sm font-bold">Labor</label></div>
                </div>`);
            const row = document.getElementById(rowId);
            row.querySelector('.main-cat-input').addEventListener('input', function() {
                const subInput = row.querySelector('.sub-cat-input');
                subInput.disabled = false;
                document.getElementById('subs-'+rowId).innerHTML = (goldenCatalog[this.value]||[]).map(i => `<option value="${i.name}">`).join('');
            });
        }

        document.getElementById('estimate-form').addEventListener('submit', async (e) => {
            e.preventDefault();
            // Payload updated to include startDate
            currentPayload = {
                project_info: { 
                    projectType: document.getElementById('project-type').value, 
                    zipCode: document.getElementById('zip-code').value, 
                    qualityLevel: document.getElementById('quality-level').value,
                    startDate: document.getElementById('start-date').value
                },
                risk_months: parseInt(document.getElementById('risk-display').textContent),
                materials: Array.from(document.querySelectorAll('.grid.gap-4')).map(row => ({
                    category: row.querySelector('.main-cat-input').value, 
                    subcategory: row.querySelector('.sub-cat-input').value,
                    quantity: parseFloat(row.querySelector('.qty-input').value) || 0, 
                    waste: parseFloat(row.querySelector('.waste-input').value) || 0,
                    labor: row.querySelector('.labor-input').checked
                }))
            };
            try {
                const response = await fetch('/api/calculate', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(currentPayload) });
                const data = await response.json();
                
                renderTable(data);
                document.getElementById('form-container').classList.add('hidden'); 
                document.getElementById('checkout-section').classList.remove('hidden');
            } catch (err) { alert("Calculation error. Please ensure all inputs are valid."); }
        });

        function editEstimate() { document.getElementById('checkout-section').classList.add('hidden'); document.getElementById('form-container').classList.remove('hidden'); }

        document.getElementById('download-pdf-btn').addEventListener('click', async () => {
            try {
                const btn = document.getElementById('download-pdf-btn');
                const originalText = btn.textContent;
                btn.textContent = "Generating...";
                
                const response = await fetch('/api/report', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify(currentPayload)
                });
                
                if (!response.ok) throw new Error("Failed to generate PDF");
                
                const blob = await response.blob();
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'CostPredict_Takeoff.pdf';
                document.body.appendChild(a);
                a.click();
                a.remove();
                window.URL.revokeObjectURL(url);
                
                btn.textContent = originalText;
            } catch (err) {
                alert("Error generating PDF. Please check your connection and try again.");
                document.getElementById('download-pdf-btn').textContent = "Print Predictive Report (PDF)";
            }
        });
    </script>
</body>
</html>
